module.exports={
  configerWebpack:{
    resolve:{
      alias:{
        'assets':'@/assests',
        'common':'@/common',
        'network':'@/network',
        'components':'@/componets',
        'views':'@/views'
      }
    }
  }
}